/* COMPANIES TYPES */
export const COMPANIES = "COMPANIES";
export const COMPANIES_LOADED = "COMPANIES_LOADED";
export const COMPANIES_TOGGLE = "COMPANIES_TOGGLE";

/* STREETS TYPES */
export const STREETS = "STREETS";
export const STREETS_LOADING = "STREETS_LOADING";
export const STREETS_TOGGLE = "STREETS_TOGGLE";

/* HOUSE TYPES */
export const HOUSES = "HOUSES";
export const HOUSES_LOADING = "HOUSES_LOADING";
export const HOUSES_TOGGLE = "HOUSES_TOGGLE";

/* APARTMENTS TYPES */
export const APARTMENTS = "APARTMENTS";
export const APARTMENTS_LOADING = "APARTMENTS_LOADING";
export const CREATE_APARTMENTS_CLIENT = "CREATE_APARTMENTS_CLIENT";
export const DELETE_APARTMENTS_CLIENT = "DELETE_APARTMENTS_CLIENT";
export const APARTMENTS_TOGGLE = "APARTMENTS_TOGGLE";
export const CLIENT_LOADING = "CLIENT_LOADING";